const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Tour = require('./models/Tour');
const Region = require('./models/Region');

// Загрузка переменных окружения
dotenv.config();

// Подключение к MongoDB
const connectDB = require('./config/db');
connectDB();

const seedDB = async () => {
  try {
    // Очистка коллекций
    await Tour.deleteMany({});
    await Region.deleteMany({});
    console.log('Коллекции tours и regions очищены');

    // Данные регионов
    const regions = [
      {
        name: 'Кавказ',
        description: 'Горный регион с живописными пейзажами и тропами для походов',
        images: ['/img/region1.jpg'],
        area: 17000,
        climate: 'Умеренный',
        coordinates: { lat: 43.5, lng: 41.5 },
      },
      {
        name: 'Сочи',
        description: 'Курортный город на Черноморском побережье с субтропическим климатом',
        images: ['/img/region2.jpg'],
        area: 3500,
        climate: 'Субтропический',
        coordinates: { lat: 43.6, lng: 39.7 },
      },
      {
        name: 'Анапа',
        description: 'Пляжный курорт, идеальный для семейного отдыха',
        images: ['/img/region3.jpg'],
        area: 1000,
        climate: 'Средиземноморский',
        coordinates: { lat: 44.9, lng: 37.3 },
      },
      {
        name: 'Геленджик',
        description: 'Живописный курорт с бухтами и винодельнями',
        images: ['/img/region4.jpg'],
        area: 1200,
        climate: 'Средиземноморский',
        coordinates: { lat: 44.6, lng: 38.1 },
      },
      {
        name: 'Краснодар',
        description: 'Центральный регион с культурными достопримечательностями',
        images: ['/img/region5.jpg'],
        area: 7500,
        climate: 'Умеренный',
        coordinates: { lat: 45.0, lng: 38.9 },
      },
    ];

    // Вставка регионов
    await Region.insertMany(regions);
    console.log('Регионы добавлены:', regions.length);

    // Данные туров
    const tours = [
      // Активные туры
      {
        title: 'Поход в горы Кавказа',
        type: 'active',
        price: 15000,
        images: ['/img/tour1.jpg'],
        description: '5-дневный треккинг по горам Кавказа',
        isFeatured: true,
        durationDays: 5,
        location: { region: 'Кавказ', coordinates: { lat: 43.5, lng: 41.5 } },
        accommodation: { type: 'camping', name: 'Горный лагерь', rating: 4, amenities: ['палатки'] },
        activities: [{ name: 'Треккинг', durationHours: 6, equipmentRequired: true }],
        excursions: [],
        includedServices: ['гид', 'питание'],
        season: { start: new Date('2025-06-01'), end: new Date('2025-09-30') },
        minGroupSize: 4,
        maxGroupSize: 12,
        difficultyLevel: 'medium',
        rating: 4.5,
        reviewsCount: 10,
      },
      {
        title: 'Восхождение на Эльбрус',
        type: 'active',
        price: 25000,
        images: ['/img/tour2.jpg'],
        description: 'Экстремальное восхождение на высшую точку России',
        isFeatured: true,
        durationDays: 7,
        location: { region: 'Кавказ', coordinates: { lat: 43.4, lng: 41.6 } },
        accommodation: { type: 'camping', name: 'Высокогорный лагерь', rating: 4.2, amenities: ['палатки'] },
        activities: [{ name: 'Альпинизм', durationHours: 8, equipmentRequired: true }],
        excursions: [],
        includedServices: ['гид', 'страховка'],
        season: { start: new Date('2025-07-01'), end: new Date('2025-08-31') },
        minGroupSize: 6,
        maxGroupSize: 10,
        difficultyLevel: 'hard',
        rating: 4.8,
        reviewsCount: 15,
      },
      {
        title: 'Велотур по предгорьям',
        type: 'active',
        price: 12000,
        images: ['/img/tour3.jpg'],
        description: 'Велосипедный тур по живописным тропам',
        isFeatured: false,
        durationDays: 3,
        location: { region: 'Кавказ', coordinates: { lat: 43.6, lng: 41.4 } },
        accommodation: { type: 'hotel', name: 'Горный приют', rating: 3.8, amenities: ['душ'] },
        activities: [{ name: 'Велоспорт', durationHours: 5, equipmentRequired: true }],
        excursions: [],
        includedServices: ['гид', 'аренда велосипедов'],
        season: { start: new Date('2025-05-01'), end: new Date('2025-10-31') },
        minGroupSize: 5,
        maxGroupSize: 15,
        difficultyLevel: 'medium',
        rating: 4.3,
        reviewsCount: 8,
      },

      // Экскурсионные туры
      {
        title: 'Экскурсия по Сочи',
        type: 'excursion',
        price: 8000,
        images: ['/img/tour4.jpg'],
        description: 'Обзорная экскурсия по достопримечательностям Сочи',
        isFeatured: true,
        durationDays: 1,
        location: { region: 'Сочи', coordinates: { lat: 43.6, lng: 39.7 } },
        accommodation: { type: 'hotel', name: 'Морской бриз', rating: 4.5, amenities: ['Wi-Fi'] },
        activities: [],
        excursions: [{ name: 'Парк Ривьера', durationHours: 2, price: 500 }],
        includedServices: ['транспорт', 'гид'],
        season: { start: new Date('2025-01-01'), end: new Date('2025-12-31') },
        minGroupSize: 2,
        maxGroupSize: 20,
        difficultyLevel: 'easy',
        rating: 4.8,
        reviewsCount: 25,
      },
      {
        title: 'Исторический тур по Краснодару',
        type: 'excursion',
        price: 6000,
        images: ['/img/tour5.jpg'],
        description: 'Прогулка по историческим местам Краснодара',
        isFeatured: true,
        durationDays: 1,
        location: { region: 'Краснодар', coordinates: { lat: 45.0, lng: 38.9 } },
        accommodation: { type: 'none', name: 'Без проживания', rating: 0, amenities: [] },
        activities: [],
        excursions: [{ name: 'Красная улица', durationHours: 3, price: 300 }],
        includedServices: ['гид'],
        season: { start: new Date('2025-01-01'), end: new Date('2025-12-31') },
        minGroupSize: 1,
        maxGroupSize: 30,
        difficultyLevel: 'easy',
        rating: 4.6,
        reviewsCount: 20,
      },
      {
        title: 'Винный тур в Геленджике',
        type: 'excursion',
        price: 10000,
        images: ['/img/tour6.jpg'],
        description: 'Дегустация вин и экскурсия по винодельням',
        isFeatured: false,
        durationDays: 2,
        location: { region: 'Геленджик', coordinates: { lat: 44.6, lng: 38.1 } },
        accommodation: { type: 'hotel', name: 'Винный дом', rating: 4.7, amenities: ['Wi-Fi'] },
        activities: [],
        excursions: [{ name: 'Винодельня Саук-Дере', durationHours: 4, price: 1000 }],
        includedServices: ['транспорт', 'дегустация'],
        season: { start: new Date('2025-04-01'), end: new Date('2025-11-30') },
        minGroupSize: 4,
        maxGroupSize: 15,
        difficultyLevel: 'easy',
        rating: 4.9,
        reviewsCount: 12,
      },

      // Кемпинг
      {
        title: 'Кемпинг у моря в Анапе',
        type: 'camping',
        price: 12000,
        images: ['/img/tour7.jpg'],
        description: 'Отдых на природе у Черного моря',
        isFeatured: true,
        durationDays: 3,
        location: { region: 'Анапа', coordinates: { lat: 44.9, lng: 37.3 } },
        accommodation: { type: 'camping', name: 'Пляжный лагерь', rating: 4, amenities: ['душ'] },
        activities: [{ name: 'Каякинг', durationHours: 3, equipmentRequired: true }],
        excursions: [],
        includedServices: ['питание', 'палатки'],
        season: { start: new Date('2025-05-01'), end: new Date('2025-10-31') },
        minGroupSize: 5,
        maxGroupSize: 15,
        difficultyLevel: 'easy',
        rating: 4.2,
        reviewsCount: 8,
      },
      {
        title: 'Кемпинг в Геленджике',
        type: 'camping',
        price: 11000,
        images: ['/img/tour8.jpg'],
        description: 'Кемпинг в живописной бухте Геленджика',
        isFeatured: false,
        durationDays: 3,
        location: { region: 'Геленджик', coordinates: { lat: 44.6, lng: 38.1 } },
        accommodation: { type: 'camping', name: 'Бухта лагерь', rating: 4.1, amenities: ['туалет'] },
        activities: [{ name: 'Сноркелинг', durationHours: 2, equipmentRequired: true }],
        excursions: [],
        includedServices: ['питание'],
        season: { start: new Date('2025-06-01'), end: new Date('2025-09-30') },
        minGroupSize: 4,
        maxGroupSize: 12,
        difficultyLevel: 'easy',
        rating: 4.4,
        reviewsCount: 10,
      },
      {
        title: 'Лесной кемпинг на Кавказе',
        type: 'camping',
        price: 13000,
        images: ['/img/tour9.jpg'],
        description: 'Кемпинг в лесах Кавказских гор',
        isFeatured: false,
        durationDays: 4,
        location: { region: 'Кавказ', coordinates: { lat: 43.7, lng: 41.3 } },
        accommodation: { type: 'camping', name: 'Лесной лагерь', rating: 3.9, amenities: ['костровая зона'] },
        activities: [{ name: 'Пешие прогулки', durationHours: 4, equipmentRequired: false }],
        excursions: [],
        includedServices: ['питание'],
        season: { start: new Date('2025-05-01'), end: new Date('2025-10-31') },
        minGroupSize: 6,
        maxGroupSize: 18,
        difficultyLevel: 'medium',
        rating: 4.3,
        reviewsCount: 7,
      },

      // Оздоровительные туры
      {
        title: 'Спа-тур в Сочи',
        type: 'health',
        price: 20000,
        images: ['/img/tour10.jpg'],
        description: 'Оздоровительный отдых в спа-центре Сочи',
        isFeatured: true,
        durationDays: 5,
        location: { region: 'Сочи', coordinates: { lat: 43.6, lng: 39.8 } },
        accommodation: { type: 'hotel', name: 'Спа-отель', rating: 4.8, amenities: ['бассейн', 'Wi-Fi'] },
        activities: [{ name: 'Спа-процедуры', durationHours: 3, equipmentRequired: false }],
        excursions: [],
        includedServices: ['питание', 'спа'],
        season: { start: new Date('2025-01-01'), end: new Date('2025-12-31') },
        minGroupSize: 2,
        maxGroupSize: 10,
        difficultyLevel: 'easy',
        rating: 4.7,
        reviewsCount: 18,
      },
      {
        title: 'Йога-ретрит в Краснодаре',
        type: 'health',
        price: 18000,
        images: ['/img/tour11.jpg'],
        description: 'Йога и медитация в экологичной зоне',
        isFeatured: false,
        durationDays: 4,
        location: { region: 'Краснодар', coordinates: { lat: 45.1, lng: 38.9 } },
        accommodation: { type: 'retreat', name: 'Йога-центр', rating: 4.5, amenities: ['вегетарианское питание'] },
        activities: [{ name: 'Йога', durationHours: 2, equipmentRequired: false }],
        excursions: [],
        includedServices: ['питание', 'инструктор'],
        season: { start: new Date('2025-03-01'), end: new Date('2025-11-30') },
        minGroupSize: 3,
        maxGroupSize: 12,
        difficultyLevel: 'easy',
        rating: 4.6,
        reviewsCount: 14,
      },
      {
        title: 'Санаторный отдых в Анапе',
        type: 'health',
        price: 22000,
        images: ['/img/tour12.jpg'],
        description: 'Лечение и отдых в санатории Анапы',
        isFeatured: false,
        durationDays: 7,
        location: { region: 'Анапа', coordinates: { lat: 44.9, lng: 37.4 } },
        accommodation: { type: 'sanatorium', name: 'Морской санаторий', rating: 4.3, amenities: ['медицинские процедуры'] },
        activities: [{ name: 'Физиотерапия', durationHours: 2, equipmentRequired: false }],
        excursions: [],
        includedServices: ['питание', 'лечение'],
        season: { start: new Date('2025-01-01'), end: new Date('2025-12-31') },
        minGroupSize: 1,
        maxGroupSize: 20,
        difficultyLevel: 'easy',
        rating: 4.4,
        reviewsCount: 16,
      },

      // Пассивные туры
      {
        title: 'Пляжный отдых в Сочи',
        type: 'passive',
        price: 10000,
        images: ['/img/tour13.jpg'],
        description: 'Расслабленный отдых на пляжах Сочи',
        isFeatured: true,
        durationDays: 3,
        location: { region: 'Сочи', coordinates: { lat: 43.5, lng: 39.7 } },
        accommodation: { type: 'hotel', name: 'Пляжный отель', rating: 4.6, amenities: ['бассейн'] },
        activities: [],
        excursions: [],
        includedServices: ['питание'],
        season: { start: new Date('2025-05-01'), end: new Date('2025-10-31') },
        minGroupSize: 1,
        maxGroupSize: 50,
        difficultyLevel: 'easy',
        rating: 4.5,
        reviewsCount: 22,
      },
      {
        title: 'Пляжный отдых в Геленджике',
        type: 'passive',
        price: 9500,
        images: ['/img/tour14.jpg'],
        description: 'Спокойный отдых на берегу моря',
        isFeatured: false,
        durationDays: 3,
        location: { region: 'Геленджик', coordinates: { lat: 44.6, lng: 38.2 } },
        accommodation: { type: 'hotel', name: 'Морской отель', rating: 4.4, amenities: ['Wi-Fi'] },
        activities: [],
        excursions: [],
        includedServices: ['питание'],
        season: { start: new Date('2025-06-01'), end: new Date('2025-09-30') },
        minGroupSize: 1,
        maxGroupSize: 40,
        difficultyLevel: 'easy',
        rating: 4.3,
        reviewsCount: 19,
      },
      {
        title: 'Отдых в Краснодаре',
        type: 'passive',
        price: 8500,
        images: ['/img/tour15.jpg'],
        description: 'Спокойный отдых в городской среде',
        isFeatured: false,
        durationDays: 2,
        location: { region: 'Краснодар', coordinates: { lat: 45.0, lng: 39.0 } },
        accommodation: { type: 'hotel', name: 'Городской отель', rating: 4.2, amenities: ['Wi-Fi'] },
        activities: [],
        excursions: [],
        includedServices: ['питание'],
        season: { start: new Date('2025-01-01'), end: new Date('2025-12-31') },
        minGroupSize: 1,
        maxGroupSize: 30,
        difficultyLevel: 'easy',
        rating: 4.1,
        reviewsCount: 15,
      },
      // Дополнительные туры для пагинации
      {
        title: 'Поход в горы 4',
        type: 'active',
        price: 16000,
        images: ['/img/tour16.jpg'],
        description: 'Еще один активный тур по Кавказу',
        isFeatured: false,
        durationDays: 5,
        location: { region: 'Кавказ', coordinates: { lat: 43.5, lng: 41.5 } },
        accommodation: { type: 'camping', name: 'Горный лагерь', rating: 4, amenities: ['палатки'] },
        activities: [{ name: 'Треккинг', durationHours: 6, equipmentRequired: true }],
        excursions: [],
        includedServices: ['гид', 'питание'],
        season: { start: new Date('2025-06-01'), end: new Date('2025-09-30') },
        minGroupSize: 4,
        maxGroupSize: 12,
        difficultyLevel: 'medium',
        rating: 4.5,
        reviewsCount: 10,
      },
      {
        title: 'Экскурсия по Сочи 4',
        type: 'excursion',
        price: 8500,
        images: ['/img/tour17.jpg'],
        description: 'Еще одна экскурсия по Сочи',
        isFeatured: false,
        durationDays: 1,
        location: { region: 'Сочи', coordinates: { lat: 43.6, lng: 39.7 } },
        accommodation: { type: 'none', name: 'Без проживания', rating: 0, amenities: [] },
        activities: [],
        excursions: [{ name: 'Олимпийский парк', durationHours: 3, price: 400 }],
        includedServices: ['гид'],
        season: { start: new Date('2025-01-01'), end: new Date('2025-12-31') },
        minGroupSize: 1,
        maxGroupSize: 30,
        difficultyLevel: 'easy',
        rating: 4.6,
        reviewsCount: 20,
      },
      {
        title: 'Кемпинг у моря 4',
        type: 'camping',
        price: 12500,
        images: ['/img/tour18.jpg'],
        description: 'Еще один кемпинг в Анапе',
        isFeatured: false,
        durationDays: 3,
        location: { region: 'Анапа', coordinates: { lat: 44.9, lng: 37.3 } },
        accommodation: { type: 'camping', name: 'Пляжный лагерь', rating: 4, amenities: ['душ'] },
        activities: [{ name: 'Каякинг', durationHours: 3, equipmentRequired: true }],
        excursions: [],
        includedServices: ['питание', 'палатки'],
        season: { start: new Date('2025-05-01'), end: new Date('2025-10-31') },
        minGroupSize: 5,
        maxGroupSize: 15,
        difficultyLevel: 'easy',
        rating: 4.2,
        reviewsCount: 8,
      },
      {
        title: 'Спа-тур в Геленджике',
        type: 'health',
        price: 21000,
        images: ['/img/tour19.jpg'],
        description: 'Оздоровительный отдых в Геленджике',
        isFeatured: false,
        durationDays: 5,
        location: { region: 'Геленджик', coordinates: { lat: 44.6, lng: 38.1 } },
        accommodation: { type: 'hotel', name: 'Спа-отель', rating: 4.8, amenities: ['бассейн', 'Wi-Fi'] },
        activities: [{ name: 'Спа-процедуры', durationHours: 3, equipmentRequired: false }],
        excursions: [],
        includedServices: ['питание', 'спа'],
        season: { start: new Date('2025-01-01'), end: new Date('2025-12-31') },
        minGroupSize: 2,
        maxGroupSize: 10,
        difficultyLevel: 'easy',
        rating: 4.7,
        reviewsCount: 18,
      },
      {
        title: 'Пляжный отдых в Анапе',
        type: 'passive',
        price: 10500,
        images: ['/img/tour20.jpg'],
        description: 'Расслабленный отдых на пляжах Анапы',
        isFeatured: false,
        durationDays: 3,
        location: { region: 'Анапа', coordinates: { lat: 44.9, lng: 37.3 } },
        accommodation: { type: 'hotel', name: 'Пляжный отель', rating: 4.6, amenities: ['бассейн'] },
        activities: [],
        excursions: [],
        includedServices: ['питание'],
        season: { start: new Date('2025-05-01'), end: new Date('2025-10-31') },
        minGroupSize: 1,
        maxGroupSize: 50,
        difficultyLevel: 'easy',
        rating: 4.5,
        reviewsCount: 22,
      },
      {
        title: 'Поход в горы 5',
        type: 'active',
        price: 17000,
        images: ['/img/tour21.jpg'],
        description: 'Треккинг по новым маршрутам Кавказа',
        isFeatured: false,
        durationDays: 5,
        location: { region: 'Кавказ', coordinates: { lat: 43.5, lng: 41.5 } },
        accommodation: { type: 'camping', name: 'Горный лагерь', rating: 4, amenities: ['палатки'] },
        activities: [{ name: 'Треккинг', durationHours: 6, equipmentRequired: true }],
        excursions: [],
        includedServices: ['гид', 'питание'],
        season: { start: new Date('2025-06-01'), end: new Date('2025-09-30') },
        minGroupSize: 4,
        maxGroupSize: 12,
        difficultyLevel: 'medium',
        rating: 4.5,
        reviewsCount: 10,
      },
      {
        title: 'Экскурсия по Краснодару 2',
        type: 'excursion',
        price: 6500,
        images: ['/img/tour22.jpg'],
        description: 'Вторая экскурсия по Краснодару',
        isFeatured: false,
        durationDays: 1,
        location: { region: 'Краснодар', coordinates: { lat: 45.0, lng: 38.9 } },
        accommodation: { type: 'none', name: 'Без проживания', rating: 0, amenities: [] },
        activities: [],
        excursions: [{ name: 'Парк Галицкого', durationHours: 3, price: 300 }],
        includedServices: ['гид'],
        season: { start: new Date('2025-01-01'), end: new Date('2025-12-31') },
        minGroupSize: 1,
        maxGroupSize: 30,
        difficultyLevel: 'easy',
        rating: 4.6,
        reviewsCount: 20,
      },
      {
        title: 'Кемпинг в Сочи',
        type: 'camping',
        price: 11500,
        images: ['/img/tour23.jpg'],
        description: 'Кемпинг на природе в Сочи',
        isFeatured: false,
        durationDays: 3,
        location: { region: 'Сочи', coordinates: { lat: 43.6, lng: 39.7 } },
        accommodation: { type: 'camping', name: 'Лесной лагерь', rating: 4, amenities: ['душ'] },
        activities: [{ name: 'Пешие прогулки', durationHours: 3, equipmentRequired: false }],
        excursions: [],
        includedServices: ['питание', 'палатки'],
        season: { start: new Date('2025-05-01'), end: new Date('2025-10-31') },
        minGroupSize: 5,
        maxGroupSize: 15,
        difficultyLevel: 'easy',
        rating: 4.2,
        reviewsCount: 8,
      },
      {
        title: 'Йога-ретрит в Геленджике',
        type: 'health',
        price: 19000,
        images: ['/img/tour24.jpg'],
        description: 'Йога и медитация в Геленджике',
        isFeatured: false,
        durationDays: 4,
        location: { region: 'Геленджик', coordinates: { lat: 44.6, lng: 38.1 } },
        accommodation: { type: 'retreat', name: 'Йога-центр', rating: 4.5, amenities: ['вегетарианское питание'] },
        activities: [{ name: 'Йога', durationHours: 2, equipmentRequired: false }],
        excursions: [],
        includedServices: ['питание', 'инструктор'],
        season: { start: new Date('2025-03-01'), end: new Date('2025-11-30') },
        minGroupSize: 3,
        maxGroupSize: 12,
        difficultyLevel: 'easy',
        rating: 4.6,
        reviewsCount: 14,
      },
      {
        title: 'Пляжный отдых в Краснодаре',
        type: 'passive',
        price: 9000,
        images: ['/img/tour25.jpg'],
        description: 'Спокойный отдых в пригороде Краснодара',
        isFeatured: false,
        durationDays: 2,
        location: { region: 'Краснодар', coordinates: { lat: 45.0, lng: 38.9 } },
        accommodation: { type: 'hotel', name: 'Городской отель', rating: 4.2, amenities: ['Wi-Fi'] },
        activities: [],
        excursions: [],
        includedServices: ['питание'],
        season: { start: new Date('2025-01-01'), end: new Date('2025-12-31') },
        minGroupSize: 1,
        maxGroupSize: 30,
        difficultyLevel: 'easy',
        rating: 4.1,
        reviewsCount: 15,
      },
    ];

    // Вставка туров
    await Tour.insertMany(tours);
    console.log('Туры добавлены:', tours.length);
    console.log('Популярные туры (isFeatured: true):', (await Tour.countDocuments({ isFeatured: true })));

    console.log('База данных успешно заполнена!');
  } catch (error) {
    console.error('Ошибка заполнения базы данных:', error);
  } finally {
    mongoose.connection.close();
  }
};

// Выполнение скрипта
seedDB();